### ISSUE TITLE
Не працює

### ISSUE THREAD

**Issue by MyTrueLogin** [kolirt/laravel-ukrposhta#1]
Client error: `GET https://ukrposhta.ua/address-classifier/get_city_by_region_id_and_district_id_and_city_ua` resulted in a `403 Forbidden` response:
API requests allowed on www.ukrposhta.ua domain only.
Я так розумію API стало закритим?

**Comment by MyTrueLogin** [comment]
Чи воно і до цього таким було?

**Comment by kolirt** [comment]
> Client error: `GET https://ukrposhta.ua/address-classifier/get_city_by_region_id_and_district_id_and_city_ua` resulted in a `403 Forbidden` response: API requests allowed on [www.ukrposhta.ua](http://www.ukrposhta.ua) domain only. Я так розумію API стало закритим?

www перед доменом хоче. відколи хз. зараз оновлю пакет

**Comment by kolirt** [comment]
> Client error: `GET https://ukrposhta.ua/address-classifier/get_city_by_region_id_and_district_id_and_city_ua` resulted in a `403 Forbidden` response: API requests allowed on [www.ukrposhta.ua](http://www.ukrposhta.ua) domain only. Я так розумію API стало закритим?

оновись до 1.0.3 і має все ок стати
